//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMC.Source
{
    using Newtonsoft.Json;
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    [JsonObject(IsReference = false)]
    public partial class SYS_Users
    {
        public SYS_Users()
        {
            this.SYS_Roles = new HashSet<SYS_Roles>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsEnabled { get; set; }
        public string Remark { get; set; }
        public string Code { get; set; }
        public string AreaName { get; set; }
    	public EntityState EntityState { get; set; }
    
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual ICollection<SYS_Roles> SYS_Roles { get; set; }
    }
}
