//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMC.Source
{
    using Newtonsoft.Json;
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    [JsonObject(IsReference = false)]
    public partial class ViewDeviceAlarm
    {
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> DeviceId { get; set; }
        public Nullable<double> AlarmDataCeiling { get; set; }
        public Nullable<double> AlarmDataFloor { get; set; }
        public Nullable<double> AlarmData { get; set; }
        public Nullable<System.DateTime> CurrentTime { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
        public System.Guid Id { get; set; }
        public string AlarmDataType_English { get; set; }
        public string AlarmDataType_Chinese { get; set; }
    	public EntityState EntityState { get; set; }
    }
}
