//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMC.Source
{
    using Newtonsoft.Json;
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    [JsonObject(IsReference = false)]
    public partial class Device
    {
        public Device()
        {
            this.AlarmRecord = new HashSet<AlarmRecord>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<System.Guid> BoilerId { get; set; }
        public string Code { get; set; }
        public string AreaName { get; set; }
    	public EntityState EntityState { get; set; }
    
        public virtual ICollection<AlarmRecord> AlarmRecord { get; set; }
    }
}
