//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMC.Source
{
    using Newtonsoft.Json;
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    [JsonObject(IsReference = false)]
    public partial class SYS_Organization
    {
        public SYS_Organization()
        {
            this.SYS_Users = new HashSet<SYS_Users>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string AreaCode { get; set; }
        public string Remark { get; set; }
        public int Level { get; set; }
    	public EntityState EntityState { get; set; }
    
        public virtual ICollection<SYS_Users> SYS_Users { get; set; }
    }
}
