//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMC.Source
{
    using Newtonsoft.Json;
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    [JsonObject(IsReference = false)]
    public partial class ViewMenu
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ParentName { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public bool IsEnabled { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    	public EntityState EntityState { get; set; }
    }
}
