@ECHO OFF
@REM 
@REM Author: tangqiao
@REM Date:   2015-12-23
@REM Purpose:backup H2SMonitor客户端程序
@REM 
@REM Usage: backup_pdb.bat <OutDir> <TargetName> 
@REM 
@REM 



IF "%2"=="" ( GOTO SHOW_USAGE )
IF "%1"=="" ( GOTO SHOW_USAGE )


@SET OUTDIR=%1
@SET TARGETNAME=%2
@SET BACKUPDIR=client-deploy
@SET BUILDDATE=%DATE:~0,10%
@SET BUILDTIME=%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%


@REM 创建备份文件夹
IF NOT EXIST %OUTDIR%\%BACKUPDIR% (MKDIR %OUTDIR%\%BACKUPDIR%)


@REM 备份pdb&exe
@ECHO 备份 %TARGETNAME%.exe
COPY %OUTDIR%%TARGETNAME%.exe %OUTDIR%\%BACKUPDIR%\
@REM COPY %OUTDIR%%TARGETNAME%.exe %OUTDIR%\%BACKUPDIR%\%BUILDDATE%\%BUILDTIME%\
@REM @ECHO 备份 %TARGETNAME%.pdb
@REM COPY %OUTDIR%%TARGETNAME%.pdb %OUTDIR%\%BACKUPDIR%\%BUILDDATE%\%BUILDTIME%\

@REM TIMEOUT /T 1
@EXIT


:SHOW_USAGE

@ECHO Usage: backup.bat OutDir TargetName

@PAUSE
@EXIT